### PR TITLE
Potential Fix for Double Navigating?

### PR DESCRIPTION
**Pull request by ZakRaymer**

### CODE REVIEW

**Comment by benminer** [comment]
This wouldn't fix it since you are just filtering out any duplicate routes (which someones we may want intentionally). Going to the root cause of the button presses is the best way to address this, imo.

**Comment by ZakRaymer** [comment]
Yeah, I think we need a way to set whether we're navigating in the router, and not allow further navigating until that process is completed, but I didn't know how to do that. So, I went with a potential quick fix for now. Though, I didn't think about same route navigating.

**Comment by ZakRaymer** [comment]
Like it has a navigating back boolean. I imagine a navigating forward boolean could do the job.

**Comment by benminer** [comment]
👍

**Pull request merged**
