### PR TITLE
documentation

### PR DESCRIPTION
**Pull request by jottenlips**

### CODE REVIEW

**Comment by jottenlips** [comment]
Let me know if I missed anything

**Comment by benminer** [comment]
Simple enough! I think we should mention that routes with `modal` as the mode don't get added to the history stack.

**Comment by benminer** [comment]
^ or even leave a comment above the example route in the README that says that.

**Comment by jottenlips** [comment]
used your poetic words 👍

**Comment by benminer** [comment]
NICE

**Comment by jottenlips** [comment]
Also added links to the example

**Pull request merged**
